spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.b886b91d59097153
            client-secret: 18ec9a7b24049281a3481eec142f2f2f3ad7e5cc
  data:
    cassandra:
      keyspace-name: main
      username: YEKmHroBLXnaZpOqmchcEQnS
      password: FGZ6Gw1-mbbeo0jEgTT.i6Lw-tEu-1uW2yhNORDzG8Dsg0e,A8oDjsUdvgnOdUUmFq-tfZF3_118SoJrcfeEjQg37CS3Qy5acOm+kCHCR2aw3bUaj2t04IZpqk+y3Zw+
      schema-action: recreate-drop-unused
      request:
        timemout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

astra.db:
  id: fd3b568f-f06f-4501-9b49-1ace519cb086-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:YEKmHroBLXnaZpOqmchcEQnS:463d8ec27552701207eef8c885f9fe1abebefcc564f015c70f30ae15c89ed833

datastax.astra:
  secure-connect-bundle: secure-connect-inbox-app.zip